/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SuppliersImport } from './routes/suppliers'
import { Route as SuccessPageImport } from './routes/successPage'
import { Route as RegisterImport } from './routes/register'
import { Route as ProfileImport } from './routes/profile'
import { Route as OrderSupplierImport } from './routes/orderSupplier'
import { Route as LoginImport } from './routes/login'
import { Route as InventoryImport } from './routes/inventory'
import { Route as CategoryImport } from './routes/category'
import { Route as AllSuppliersImport } from './routes/allSuppliers'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SuppliersRoute = SuppliersImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRoute,
} as any)

const SuccessPageRoute = SuccessPageImport.update({
  id: '/successPage',
  path: '/successPage',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const OrderSupplierRoute = OrderSupplierImport.update({
  id: '/orderSupplier',
  path: '/orderSupplier',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InventoryRoute = InventoryImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRoute,
} as any)

const CategoryRoute = CategoryImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRoute,
} as any)

const AllSuppliersRoute = AllSuppliersImport.update({
  id: '/allSuppliers',
  path: '/allSuppliers',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/allSuppliers': {
      id: '/allSuppliers'
      path: '/allSuppliers'
      fullPath: '/allSuppliers'
      preLoaderRoute: typeof AllSuppliersImport
      parentRoute: typeof rootRoute
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryImport
      parentRoute: typeof rootRoute
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/orderSupplier': {
      id: '/orderSupplier'
      path: '/orderSupplier'
      fullPath: '/orderSupplier'
      preLoaderRoute: typeof OrderSupplierImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/successPage': {
      id: '/successPage'
      path: '/successPage'
      fullPath: '/successPage'
      preLoaderRoute: typeof SuccessPageImport
      parentRoute: typeof rootRoute
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allSuppliers': typeof AllSuppliersRoute
  '/category': typeof CategoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/orderSupplier': typeof OrderSupplierRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/successPage': typeof SuccessPageRoute
  '/suppliers': typeof SuppliersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allSuppliers': typeof AllSuppliersRoute
  '/category': typeof CategoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/orderSupplier': typeof OrderSupplierRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/successPage': typeof SuccessPageRoute
  '/suppliers': typeof SuppliersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/allSuppliers': typeof AllSuppliersRoute
  '/category': typeof CategoryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/orderSupplier': typeof OrderSupplierRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/successPage': typeof SuccessPageRoute
  '/suppliers': typeof SuppliersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allSuppliers'
    | '/category'
    | '/inventory'
    | '/login'
    | '/orderSupplier'
    | '/profile'
    | '/register'
    | '/successPage'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allSuppliers'
    | '/category'
    | '/inventory'
    | '/login'
    | '/orderSupplier'
    | '/profile'
    | '/register'
    | '/successPage'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/allSuppliers'
    | '/category'
    | '/inventory'
    | '/login'
    | '/orderSupplier'
    | '/profile'
    | '/register'
    | '/successPage'
    | '/suppliers'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllSuppliersRoute: typeof AllSuppliersRoute
  CategoryRoute: typeof CategoryRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OrderSupplierRoute: typeof OrderSupplierRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SuccessPageRoute: typeof SuccessPageRoute
  SuppliersRoute: typeof SuppliersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllSuppliersRoute: AllSuppliersRoute,
  CategoryRoute: CategoryRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OrderSupplierRoute: OrderSupplierRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SuccessPageRoute: SuccessPageRoute,
  SuppliersRoute: SuppliersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/allSuppliers",
        "/category",
        "/inventory",
        "/login",
        "/orderSupplier",
        "/profile",
        "/register",
        "/successPage",
        "/suppliers"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/allSuppliers": {
      "filePath": "allSuppliers.tsx"
    },
    "/category": {
      "filePath": "category.tsx"
    },
    "/inventory": {
      "filePath": "inventory.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/orderSupplier": {
      "filePath": "orderSupplier.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/successPage": {
      "filePath": "successPage.tsx"
    },
    "/suppliers": {
      "filePath": "suppliers.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
